project:
  type: website
  resources:
    - _routes.json
    - _extensions/PHBern-RConrardy/phbern/cloudflare/allowed-ip-ranges.csv
    - resources_free/**
    - resources_non_free/**

website:
  title: "TUB – Digitalität"
  navbar:
    left:
      - href: index.qmd
        text: Home

institut: "Sekundarstufe II"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
